development:
    AWS_ACCESS_KEY_ID: 'PASTE AWS_ACCESS_KEY_ID HERE'
    AWS_SECRET_ACCESS_KEY: 'PASTE AWS_SECRET_ACCESS_KEY HERE'
    S3_BUCKET: 'dopest_development'
test:
    AWS_ACCESS_KEY_ID: 'PASTE AWS_ACCESS_KEY_ID HERE'
    AWS_SECRET_ACCESS_KEY: 'PASTE AWS_SECRET_ACCESS_KEY HERE'
    S3_BUCKET: 'dopest_test'
production:
    AWS_ACCESS_KEY_ID: 'PASTE AWS_ACCESS_KEY_ID HERE'
    AWS_SECRET_ACCESS_KEY: 'PASTE AWS_SECRET_ACCESS_KEY HERE'
    S3_BUCKET: 'dopest_production'
