development:
    AWS_ACCESS_KEY_ID: 'PASTE AWS_ACCESS_KEY_ID HERE'
    AWS_SECRET_ACCESS_KEY: 'PASTE AWS_SECRET_ACCESS_KEY HERE'
test:
    AWS_ACCESS_KEY_ID: 'PASTE AWS_ACCESS_KEY_ID HERE'
    AWS_SECRET_ACCESS_KEY: 'PASTE AWS_SECRET_ACCESS_KEY HERE'
production:
    AWS_ACCESS_KEY_ID: 'PASTE AWS_ACCESS_KEY_ID HERE'
    AWS_SECRET_ACCESS_KEY: 'PASTE AWS_SECRET_ACCESS_KEY HERE'
